---
title: "Data Manipulation"
output: github_document
---
```{r echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Read some data

This document will show how to *manipulate* data.

Import the two datasets that we are going to manipulate.

```{r}
litter_df = 
   read_csv("data/FAS_litters.csv", na = c("NA","", "."))

litter_df = janitor::clean_names(litter_df)

pups_df = 
  read_csv("data/FAS_pups.csv", na = c("NA", "", "."))
```


##'select'
use 'select()' to select variable 

```{r}
select(litter_df, group, litter_number, gd0_weight)

```


```{r}
select(litter_df, group:gd18_weight)
```

```{r}
select(litter_df, -pups_survive)
```

```{r}
select(litter_df, starts_with("gd"))
select(litter_df, contains("pups"))
```

```{r}
select(litter_df, GROUP = group)

rename(litter_df, GROUP = group)

select(litter_df, litter_number, gd0_weight, everything())

relocate(litter_df, litter_number, gd0_weight)
```

```{r}
select(pups_df, litter_number, sex, pd_ears)

```



## 'filter'
```{r}
filter(litter_df, gd_of_birth == 20)
filter(litter_df, gd_of_birth == 19)
```


```{r}
filter(litter_df, pups_born_alive > 8)
filter(litter_df, pups_born_alive >= 8)
```



```{r}
filter(litter_df,pups_born_alive != 9)
```

```{r}
filter(litter_df, group == "Low8")
filter(litter_df, group %in% c("Low7","Low8"))
```

```{r}
filter(litter_df, group %in% c("Low7", "Low8"), pups_born_alive ==8)
```

## missing data
```{r}
drop_na(litter_df)

drop_na(litter_df,gd0_weight)
```

##learning assessment
```{r}
filter(pups_df, Sex == 1)
filter(pups_df, pd_walk < 11, Sex ==2)
```

##'mutate'
```{r}
mutate(litter_df, wt_gain = gd18_weight - gd0_weight)

mutate(litter_df, sq_pups = pups_born_alive^2)

mutate(litter_df, str_to_lower(group))

mutate(
  litter_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

```{r}
```



##arrange
```{r}
arrange(litter_df, gd0_weight)

arrange(litter_df, desc(gd0_weight))

arrange(litter_df, pups_born_alive, gd0_weight)
```



```{r}

```


##piping
```{R}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", "", ".")) %>% 
  janitor::clean_names() |>
  select(-pups_born_alive) |>
filter(group == "Con7") |>
mutate(
  wt_gain = gd18_weight - gd0_weight
)


```

```{r}
read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |>
  mutate(wt_gain = gd18_weight - gd0_weight) |>
  lm(wt_gain ~ pups_born_alive, data = _)
```

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", "", ".")) %>% 
  janitor::clean_names() |>
  mutata(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
    |>
      select(-pups_born_alive) |>
      filter(group == "Con7")
    
    write_csv(litters_df, "data/cleaned_fas_litters.csv")
  )
```


