this documnet will show how to tidy data.



## examples of pivot_longer
```{r}
library(haven)
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()

```

This needs to go from wide to long format.

```{r}
library(haven)
library(tidyverse)
pulse_tify_df = 
    pulse_df |>
    pivot_longer(
      cols= bdi_score_bl:bdi_score_12m,
      names_to = "visit",
      values_to = "bdi_score",
      names_prefix = "bdi_score_"
    ) |>
    mutate(
      visit = replace(visit, visit == "bl", "00m")
    )
```


Do one more example
```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", "",".")) |>
  janitor::clean_names() |>
  pivot_longer(
    cols = gd0_weight:gd18_weight,
    names_to = "gd_time",
    values_to = "weight"
  ) |>
    mutate(
      gd_time = case_match(
        gd_time,
        "gd0_weight" ~ 0,
        "gd18_weight" ~ 18
      )
    )
```


##pivot wider
make analysis result table.

```{r}
analysis_df = 
  tibble(
    group = c("treatment", "treatment","control","control"),
    time = c("pre","post","pre", "post"),
    mean = c(4,10,4.2, 5)
    
  )
```

```{r}
analysis_df |>
  pivot_wider(
    names_from = time,
    values_from = mean
  ) |>
  knitr::kable()
```


## Bind tables.
```{r}
library(readxl)
fellowship_ring = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers = 
  read_excel("data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king = 
  read_excel("data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")

lotr_df = 
  bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
    pivot_longer(
      cols= female:male,
      names_to = "gender",
      values_to = "words"
    )|>
    relocate(movie) |>
    mutate(race = str_to_lower(race))
              
```

## Join FAS dataset
```{r}
litter_df = 
  read_csv("data/FAS_litters.csv", na=c("NA", ".","")) |>
  janitor::clean_names() |>
  mutate(
    wt_gain = gd18_weight - gd0_weight
  ) |>
  separate(
    group, into = c("does", "day_of_treatment"),sep = 3
  )
```

import "pups"

```{r}
pups_df = 
  read_csv("data/FAS_pups.csv", na=c("NA", ".","")) |>
             janitor::clean_names() |>
             mutate(
               sex = case_match(
                 sex, 
                 1 ~ "male",
                 2~"female"
               )
             )
    
```

## join the dataset
```{r}
fas_df = 
  left_join(pups_df, litter_df, by = "litter_number") |>
  relocate(litter_number, does,day_of_treatment)
```

